import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import { ChatSidebar } from "@/components/ui/ChatSidebar";
import { ChatButton } from "@/components/ui/ChatButton";
import { ChatUIWrapper } from "@/components/ui/ChatUIWrapper";
import { SidebarProvider } from "@/components/ui/sidebar";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({  children,}: Readonly<{
  children: React.ReactNode;
  
}>) {
  
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Script strategy="afterInteractive" src="https://cdn.platform.openai.com/deployments/chatkit/chatkit.js"></Script>
          {children}

          {/* <SidebarProvider> */}
            <ChatUIWrapper />
          {/* </SidebarProvider> */}

          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
